vich_uploader:
    db_driver: orm

    mappings:
        room:
            uri_prefix: /images/room
            upload_destination: '%kernel.project_dir%/public/images/room'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
